on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: eascr.azurecr.io
        username: ${{ secrets.acr_eascr_username }}
        password: ${{ secrets.acr_eascr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t eascr.azurecr.io/eascluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push eascr.azurecr.io/eascluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_eascluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep easclusterb53a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace easclusterb53a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: easclusterb53a
        container-registry-url: eascr.azurecr.io
        container-registry-username: ${{ secrets.acr_eascr_username }}
        container-registry-password: ${{ secrets.acr_eascr_password }}
        secret-name: easclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: easclusterb53a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          eascr.azurecr.io/eascluster:${{ github.sha }}
        imagepullsecrets: |
          easclusterdockerauth